title: Pentaho Platform JavaScript APIs
description: > # this means to ignore newlines until "baseurl:"
  The Pentaho Platform JavaScript APIs are intended and provide bla bla bla.

theme: jekyll-theme-cayman

# Build settings
markdown: kramdown

exclude:
  - Gemfile
  - Gemfile.lock

safe: true
